-- SCRIPT DE CREACIÓN DE LA BASE DE DATOS

CREATE TABLE Users (
    UUID CHAR(36) PRIMARY KEY,
    Username VARCHAR(100) UNIQUE NOT NULL,
    Password TEXT NOT NULL
);

CREATE TABLE Movies (
    UUID CHAR(36) PRIMARY KEY,
    Nombre VARCHAR(200) NOT NULL,
    Year INTEGER NOT NULL,
    Rating VARCHAR(10) DEFAULT "Not Rated",
    ImdbScore REAL,
    ImdbURL TEXT UNIQUE NOT NULL,
    Runtime INTEGER NOT NULL,
    Plot TEXT NOT NULL
);

CREATE TABLE Scores (
    UserId CHAR(36) NOT NULL REFERENCES Users(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    MovieId CHAR(36) NOT NULL REFERENCES Movies(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    Score REAL NOT NULL CHECK (Score BETWEEN 0 AND 10),
    PRIMARY KEY (UserId, MovieId)
);

CREATE TABLE WatchLists (
    UUID CHAR(36) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    UserId INTEGER NOT NULL REFERENCES Users(UUID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Movie_List (
    ListId CHAR(36) NOT NULL REFERENCES WatchLists(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    MovieId CHAR(36) NOT NULL REFERENCES Movies(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (ListId, MovieId)
);

CREATE TABLE Genres (
    UUID CHAR(36) PRIMARY KEY,
    Name VARCHAR (100) NOT NULL
);

CREATE TABLE Movie_Genre (
    MovieId CHAR(36) NOT NULL REFERENCES Movies(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    GenreId CHAR(36) NOT NULL REFERENCES Genres(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (MovieId, GenreId)
);
